### ISSUE TITLE
Measure Time on individual pages?

### ISSUE THREAD

**Issue by iuewebadmin** [robflaherty/riveted#20]
Hello!  Is the time measured only per session?  Or are pages visited also factored in?  For example, if I wanted to see how long users were staying on a particular page, will this plugin allow me to do that?  Or is that a job for your screentime plugin?

Thanks so much!  It's incredible that you've offered these amazing plugins to everyone.  Much appreciated!

**Comment by robflaherty** [comment]
Hey - yes, you can view time per page, too. One way is to go to the Events section, click Riveted, and add a Secondary Dimension of 'Page'. This should show you a list of pages and the total active time for each page.

**Comment by iuewebadmin** [comment]
That's perfect, thanks so much!  And thanks for the quick reply. :)

**Comment by iuewebadmin** [comment]
Quick followup question... so when I'm looking at Behavior > Events > Rivited > Time Spent, all the counts I'm seeing are per page right?  So if I look at the 5 second row, the total events are the total events that a user has spent 5 seconds on a single page or 5 seconds total on the site?  If per page, is there a way to see a users whole session time?

The reason I ask is that the recommended blog post (https://medium.com/google-analytics/how-to-track-engaged-time-in-google-analytics-84d9981920da) suggests that the report is showing total engaged time per session, not per page, which is actually why I initially asked if I could even see total "riveted" time by page.  Having a little trouble understanding how the data is being collected/processed.

Thanks so much!

**Comment by robflaherty** [comment]
If you follow the instructions above you should see something like the following screenshot. For each URL, Event Value is the total number of active seconds spent on the page. If you divide that number by the number of unique events (e.g., for the first URL 237,215 / 2,096) you'll get the average number of active seconds per page.

![image](https://cloud.githubusercontent.com/assets/159644/8600342/85d1ee74-2633-11e5-8833-f25a6f838498.png)

**Comment by robflaherty** [comment]
For average riveted time per session you just have to divide the total Riveted Event Value by the number of unique events. In this example, the average riveted time per session is 92.5 seconds.
![screen shot 2015-07-09 at 12 16 29 pm](https://cloud.githubusercontent.com/assets/159644/8600569/7646c6a4-2634-11e5-88ca-9df504c00c99.png)

**Comment by iuewebadmin** [comment]
Ah, I see now.  Thanks for the explanation (and for taking the time)!
