### ISSUE TITLE
Custom dimensions on Riveted events

### ISSUE THREAD

**Issue by aguynamedben** [robflaherty/riveted#23]
Hi Rob, thanks for you excellent work on this library, including the writeup on how it's used. I'm finding Riveted extremely valuable.

I had a question—is there an easy way to send Custom Dimensions along with the hits Riveted generates? My use case is this: I want to track which sections of my website (Blog, FAQ, About Us, etc.) people are spending time on. I saw the issue about seeing which pages people spend time on, but I'm curious in tracking sections of my website.

I'm sending a Custom Dimension with my pageview event, but when I look at the subsequent Riveted events, those hits don't have my Custom Dimension being set. Any pro-tips here would be greatly appreciated.

Thanks again for your epic work.

**Comment by robflaherty** [comment]
Hey,

Are you setting the custom dimension with the `set` command (ex: `ga('set', 'dimension', 'custom data');`) or are you setting it on the pageview command? The former defines the custom dimension globally and it will automatically apply to GA events. The latter only applies the dimension to the pageview.

**Comment by aguynamedben** [comment]
Oh yeah, you are correct... I am using the "set" command.

> In some cases, you might want to send a custom dimension or metric with all the hits on a given page (or for the lifetime of the tracker object). In this case, you can set the custom dimension or metrics using the set command

Cool, sorry for the RTFM question, I must have skipped right over that when reading about the different GA event scopes. Thanks for this library, it's really helpful.

**Comment by robflaherty** [comment]
No worries! The custom dimension stuff is confusing. Glad to hear you like the library :)
